version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped